Kips code cleanup
arvalaan/HealingRituals pull request #1
Opened 2021-08-16 17:28 UTC by kippetje2000

Have a look if you like it

2021-08-21 20:23 UTC, arvalaan requested changes

2021-08-21 20:23 UTC, arvalaan commented on Defs/ResurrectionRitual/ResurrectionRitual_Ritual.xml
> +		<allowDuplicates>true</allowDuplicates>
<allowDuplicates> should be false.

2021-08-21 20:23 UTC, arvalaan commented on Defs/ResurrectionRitual/ResurrectionRitual_Ritual.xml
> +		<ritualObligationTriggers>
I feel like there shouldn't be an obligationTrigger for resurrection. It should be a choice, not an expectation

2021-08-23 17:32 UTC, kippetje2000 commented on Defs/ResurrectionRitual/ResurrectionRitual_Ritual.xml
> +		<allowDuplicates>true</allowDuplicates>
I did and it keeps giving errors so im not sure where it went wrong

2021-08-23 17:34 UTC, kippetje2000 commented on Defs/ResurrectionRitual/ResurrectionRitual_Ritual.xml
> +		<ritualObligationTriggers>
Is this that message on the right of the screen?

2021-08-23 19:17 UTC, arvalaan commented
I'll merge your PR and look into it :)

2021-08-23 19:17 UTC, merged